const colleaguesDB = [
  {
    fname: "Faranak",
    lname: "Rahimi",
    email: "faranak.rahimi@powercoders.org",
    job: "Teacher",
    hobby: "Swimming",
    quote: "Hi, you!",
    linkedIn: "https://www.linkedin.com/in/faranak-rahimi-6068a218a/",
    imgUrl: "img/1.jpg",
  },
  {
    fname: "Kateryna",
    lname: "Shyrokova",
    email: "Kateryna.Shyrokova@powercoders.org",
    job: "Unemployed",
    hobby: "gym",
    quote: "The only easy day was yesterday",
    linkedIn: "https://www.linkedin.com/in/katerynashyrokova/",
    imgUrl: "img/2.jpg",
  },
  {
    fname: "Meleknur",
    lname: "Ozgu",
    email: "Meleknur.Ozgu@powercoders.org",
    job: "Software Tester",
    hobby: "Squash",
    quote: "Life is a balance between holding on and letting go",
    linkedIn: "https://www.linkedin.com/in/meleknur/",
    imgUrl: "img/5.jpg",
  },
  {
    fname: "Gebremedhin",
    lname: "Kahsay",
    email: "Gebremedhin.Kahsay@powercoders.org",
    job: "Java Developer",
    hobby: "hiking",
    quote: "My awesome quote",
    linkedIn: "https://www.linkedin.com",
    imgUrl: "img/3.jpg",
  },
  {
    fname: "Viktor",
    lname: "Khrapal",
    email: "Viktor.Khrapal@powercoders.org",
    job: "QA",
    hobby: "Table games",
    quote: "織田信長はやったし、私もできる",
    linkedIn: "https://www.linkedin.com",
    imgUrl: "img/4.jpg",
  },
  {
    fname: "Oleksandra",
    lname: "Honchar",
    email: "oleksandra.honchar@powercoders.org",
    job: "Software Developer",
    hobby: "Design",
    quote: "Let's go beyond expectations",
    linkedIn: "https://www.linkedin.com/in/oleksandra-honchar/",
    imgUrl: "img/6.jpg",
  },
  {
    fname: "Ali",
    lname: "Dinc",
    email: "Ali.Dinc@powercoders.org",
    job: "Cloud Developer",
    hobby: "Football",
    quote: "My awesome quote",
    linkedIn: "https://www.linkedin.com/in/oleksandra-honchar/",
    imgUrl: "img/7.jpg",
  },
  {
    fname: "Yücel",
    lname: "ISBARAN",
    email: "Yucel.ISBARAN@powercoders.org",
    job: "Blockchain Developer",
    hobby: "Basketball",
    quote: "I am Blockchain Enthusiast",
    linkedIn: "https://twitter.com/yucelisking",
    imgUrl: "img/8.jpg",
  },
];

export { colleaguesDB };
